### ISSUE TITLE
Fix CityEventsChart component not rendering Y-axis correctly 

### ISSUE THREAD

**Issue by timone019** [AJSorbello/meet#1]
In your src/components/CityEventsChart.js Line 23: 

You have an extra front parenthesis after split: 
const city = location.split((/, | - /))[0];

the split method is called with the parameter (, | - ), enclosed within parentheses. 

Fix! 
try: 
const city = location.split(/, | - /)[0];

the split method is called with the regular expression /, | - / without parentheses.

**Comment by AJSorbello** [comment]
fix something else
